### PR TITLE
bump transformers

### PR DESCRIPTION
**Pull request by flozi00**

### CODE REVIEW

**Comment by Timoeller** [comment]
Thanks for the PR.

Lets wait for the CI to pass. Nevertheless our FAMR CI is not fully comprehensive. It is necessary to do a couple of other checks, e.g. run test/benchmarks/question_answering_accuracy.py
Could you do that and post results here?

**Comment by flozi00** [comment]
yeah, sure
will do the benchmark later
tested it locally and seems to be compatible, did not found anything in the release notes what could break

**Comment by flozi00** [comment]
`{'tokens': ['▁Some', '▁Text', '▁with', 'neverseentokens', '▁plus', '▁', ...]} != {'tokens': ['▁Some', '▁Text', '▁with', '▁', 'neverseentokens', '▁plus', ...]}`

The test save load is failing
seems strange

**Comment by Timoeller** [comment]
Hey @flozi00 sorry for the late reply. I shortly looked at it and yes, this seems strange indeed. 
Do you think it is a tokenizers issue? 
Unfortunately we do not have time to look into it in detail ourselves the next 2 weeks. We will gladly do so afterwards. Any help from your side would be appreciated.

**Comment by Timoeller** [comment]
Hey @flozi00 do you have any new insights into why the HF Tokenizer has this behaviour?
Otherwise we would soon take over.

**Comment by stefan-it** [comment]
Hi @Timoeller and @flozi00 ,

I talked with @LysandreJik about this issue and a fix is to pass 'from_slow=True` during init. of the tokenizer. So locally, the following is running and the test case is passing:

```python
t = Tokenizer.load(lang_name, lower_case=False, use_fast=True, from_slow=True)
```

Tested with 4.4.2 and 4.5.0 :)

**Comment by Timoeller** [comment]
How is that possible @stefan-it 
This bug is lying around since weeks and I just created https://github.com/huggingface/transformers/issues/11112

Ok so I can close that issue already :D

**Comment by Timoeller** [comment]
Hey @stefan-it I cannot reproduce the fix when running in a fresh colab with: !pip install transformers[sentencepiece]==4.5.0

```
from transformers import AutoTokenizer, AutoConfig


def test_tokenizers():
    basic_text = "Some Text with neverseentokens and more"
    tokenizer_orig = AutoTokenizer.from_pretrained("xlnet-base-cased")
    config_orig = AutoConfig.from_pretrained("xlnet-base-cased")
    tokenizer_orig.add_tokens(new_tokens=["neverseentokens"])
    tokenizer_orig.save_pretrained("testsave")
    config_orig.save_pretrained("testsave")
    tokens_before = tokenizer_orig.encode_plus(basic_text).encodings[0].tokens
    
    tokenizer_loaded = AutoTokenizer.from_pretrained("testsave", use_fast=True, from_slow=True)
    tokens_after = tokenizer_loaded.encode_plus(basic_text).encodings[0].tokens

    print(f"Before loading: {tokens_before}")
    print(f"After loading: {tokens_after}")
    assert tokens_before == tokens_after

if __name__ == "__main__":
    test_tokenizers()
```

**Comment by stefan-it** [comment]
Hm, I used this code:

```python
from farm.modeling.tokenization import Tokenizer

lang_names = ["xlnet-base-cased"]
tokenizers = []
for lang_name in lang_names:
    t = Tokenizer.load(lang_name, lower_case=False, use_fast=True, from_slow=True)
    t.add_tokens(new_tokens=["neverseentokens"])
    tokenizers.append(t)

basic_text = "Some Text with neverseentokens plus !215?#. and a combined-token_with/chars"

for tokenizer in tokenizers:
    save_dir = f"testsave"
    tokenizer_type = tokenizer.__class__.__name__
    tokenizer.save_pretrained(save_dir)
    tokenizer_loaded = Tokenizer.load(save_dir, tokenizer_class=tokenizer_type)
    encoded_before = tokenizer.encode_plus(basic_text).encodings[0]
    encoded_after = tokenizer_loaded.encode_plus(basic_text).encodings[0]
    data_before = {"tokens": encoded_before.tokens,
                    "offsets": encoded_before.offsets,
                    "words": encoded_before.words}

    print("Debug: data_before:", data_before)

    data_after = {"tokens": encoded_after.tokens,
                    "offsets": encoded_after.offsets,
                    "words": encoded_after.words}

    print("Debug: data_after:", data_after)

    assert data_before == data_after

```

And this snippet to test the HF side:

```python
from transformers import XLNetTokenizerFast

pretrained_model_name_or_path = "xlnet-base-cased"

tokenizer = XLNetTokenizerFast.from_pretrained(pretrained_model_name_or_path, keep_accents=True, from_slow=True)

tokenizer.add_tokens(new_tokens=["neverseentokens"])

basic_text = "Some Text with neverseentokens plus !215?#. and a combined-token_with/chars"

encoded_before = tokenizer.encode_plus(basic_text).encodings[0]

data_before = {"tokens": encoded_before.tokens,
               "offsets": encoded_before.offsets,
               "words": encoded_before.words}

print("Debug: data_before:", data_before)

tokenizer.save_pretrained("./tokenizer-test")

new_tokenizer = XLNetTokenizerFast.from_pretrained("./tokenizer-test")

encoded_after = new_tokenizer.encode_plus(basic_text).encodings[0]

data_after = {"tokens": encoded_after.tokens,
              "offsets": encoded_after.offsets,
              "words": encoded_after.words}

print("Debug: data_after:", data_after)
```

:thinking:

**Comment by Timoeller** [comment]
Ah, the first time you load the tokenizer you use from_slow.

I just used from_slow=True when loading the already saved model!

Now it also works for me. Thanks Stefan, great help

**Pull request closed without merging**
