### PR TITLE
Use Path instead of String in ONNXAdaptiveModel

### PR DESCRIPTION
**Pull request by skiran252**
load_dir should be a Path variable

### CODE REVIEW

**Review by Timoeller — COMMENTED** [review]
Thanks for the addition.

It currently only affects the ONNXAdaptiveModel. Did you check in our "normal" AdaptiveModel as well? If the changes and tests there become too complex, we can also move forward with just this PR.

**Comment by Timoeller** [comment]
Again thanks for the addition, really appreciate effort coming from external developers. Some feedback for future OSS contributions though:
I changed the title of the PR - it is good practice to make the title more informative. 
Next time please also add slightly more description in the PR body, e.g. what caused the error or even link it to an open issue with a bug report.
Thanks

**Comment by skiran252** [comment]
> Again thanks for the addition, really appreciate effort coming from external developers. Some feedback for future OSS contributions though:
> I changed the title of the PR - it is good practice to make the title more informative.
> Next time please also add slightly more description in the PR body, e.g. what caused the error or even link it to an open issue with a bug report.
> Thanks

Ya sure. thanks for the suggestion.

**Comment by skiran252** [comment]
> Thanks for the addition.
> 
> It currently only affects the ONNXAdaptiveModel. Did you check in our "normal" AdaptiveModel as well? If the changes and tests there become too complex, we can also move forward with just this PR.

looks like this just affects ONNXAdaptiveModel and should be a simple change if done on that class.

**Review by Timoeller — APPROVED** [review]
OK, then lets merge.

**Pull request merged**
