### PR TITLE
WIP Add fast rust tokenizers

### PR DESCRIPTION
**Pull request by tholor**
Let's see if we can get the new, fast tokenizers from huggingface integrated in a nice way :) 
Speed seems promising and could help to solve #157

### CODE REVIEW

**Comment by Timoeller** [comment]
We will continue on this PR. Having faster data processing is relevant to us.

**Comment by tholor** [comment]
The serialization issue that prevented multiprocessing (and therefore integration in FARM) has been resolved in https://github.com/huggingface/tokenizers/pull/272. The basic test of fast tokenization seems to work within this branch now :tada: . 

Let's move ahead once there's a new pypi release of `tokenizers` and the version is also upgraded in `transformers`.

**Comment by tholor** [comment]
From a quick check, the offsets implemented in `tokenizers` can also deal with special chars / [UNK] (see #421).

```
from tokenizers import (ByteLevelBPETokenizer,
                         CharBPETokenizer,
                          SentencePieceBPETokenizer,
                          BertWordPieceTokenizer)

tokenizer = BertWordPieceTokenizer("bert-base-uncased-vocab.txt", lowercase=True)
text = "Hello, y'all! How are you 😁 ?"
output = tokenizer.encode("Hello, y'all! How are you 😁 ?")
print(output.ids, output.tokens, output.offsets)
print(output.tokens[10])
print(output.offsets[10])
print(text[26:27])
print(text[0:5])
```

**Comment by Timoeller** [comment]
It seems that RUST tokenizers are officially in transformers. https://github.com/huggingface/transformers/releases/tag/v3.0.0

Am I right in assuming we can use this functionality and fix #420 + #421 ? Would love to see some progress here.

**Comment by tholor** [comment]
Yes, seems good to go. The tokenizers version in transformers is now pinned to 0.8.0rc4 (which should already have proper serialization)

**Comment by PhilipMay** [comment]
Damn. I just saw I had the same in mind with this PR: https://github.com/deepset-ai/FARM/pull/482

**Comment by Timoeller** [comment]
Yes totally. Feel free to re use the tests in your PR.

**Comment by tholor** [comment]
Closing this one as we continued in #482

**Pull request closed without merging**
