### PR TITLE
Fix and document Inferencer usage and pool handling

### PR DESCRIPTION
**Pull request by PhilipMay**
This is the 2nd part of PR #403 

## TODO
- [x] check examples 
- [x] check call in `fit_s3e_on_corpus`
- [x] check other documentation
- [x] sould other code be changed to close pool
- [x] must be merged with PR #430
- [ ] update `docs/basic_usage.rst`
- [ ] update `docs/examples.rst`
- [ ] update `tutorials/1_farm_building_blocks.ipynb`
- [ ] write explicit example in doc and tell the user how to use this

### CODE REVIEW

**Comment by tanaysoni** [comment]
Hi @PhilipMay, I added a suggestion commit with a call to the `close_multiprocessing_pool()` each time we use the Inferencer. In that case, we might not need the warning comments. What do you think?

**Comment by PhilipMay** [comment]
> Hi @PhilipMay, I added a suggestion commit with a call to the `close_multiprocessing_pool()` each time we use the Inferencer. In that case, we might not need the warning comments. What do you think?

Well, that does not fully work because you would have to wrap the code into a try and finally block to even close the pool when an exception is raised.

**Comment by PhilipMay** [comment]
And to avoid this kind of "ugly and complicated" code I would better not open a pool... So the example is easy to read.

**Comment by tanaysoni** [comment]
Hi @PhilipMay, 

In the case of exception in the Inferencer, the example scripts would crash, terminating all the Python subprocesses. For instance, the following script should exit clean without any zombie processes.

```python
results = inferencer.inference_from_dicts(qa_input)
print(results)
raise Exception  # scripts exits here
inferencer.close_multiprocessing_pool()
```

**Comment by PhilipMay** [comment]
@tanaysoni Yes I agree. In the example it does not cause any direct problems. But IMO an example should be something that can be taken and put into something bigger. If placed in a real life server environment this might cause an ugly memory leak if not handled correctly. But we already had this discussion on an other PR if I remember correctly.

**Comment by PhilipMay** [comment]
So what do you suggest we can do with this uncompleted PR? In which direction should we go?

**Comment by tanaysoni** [comment]
Hi @PhilipMay, IMO we add a call to `close_multiprocessing_pool()` in each example along with a single line comment mentioning it's important to close the pool. Additionally, we can write a detailed example explaining more details about the Pool behavior. What do you think?

**Comment by PhilipMay** [comment]
Ok. Thanks. 👍

**Pull request merged**
