### PR TITLE
CI OOM Fix with smaller Model

### PR DESCRIPTION
**Pull request by PhilipMay**
CI is running OOM. See here #385 

This might be a fix. It is using a smaller model (`distilbert-base-cased` and `albert-base-v2`). See here: https://huggingface.co/transformers/pretrained_models.html

### CODE REVIEW

**Comment by PhilipMay** [comment]
Well - it can not load `distilbert-base-cased`. Is that "normal"?

**Comment by Timoeller** [comment]
FARM can load "distilbert-base-uncased" but not for LM finetuning.

[In the corresponding LM finetuning test](https://github.com/deepset-ai/FARM/blob/master/test/test_lm_finetuning.py#L43) we are loading:
- `language_model = LanguageModel.load(lang_model)` works with distilbert
 - `lm_prediction_head = BertLMHead.load(lang_model)` doesnt work since we load a BertConfig instead of a disttilbertconfig...

In any case, we already resolved the OOM CI issues when moving to azure pipelines. I suspect something changed there under the hood and we need to take a closer look. We might be able to resolve this by tomorrow.

**Comment by PhilipMay** [comment]
Could you temporarily deactivate this test? 

ˋ@pytest.mark.skip(reason="no way of currently testing this")ˋ

**Comment by Timoeller** [comment]
I am working on a fix in #392. When the test pass there we can rerun the pipelines for the other PRs

**Comment by Timoeller** [comment]
Hey @PhilipMay updating to torch==1.5.0 seems to resolve OOM issues. Lets rerun the tests and then merge the other open PRs.

I would prefer to close this PR since 
- we want to test lm finetuning with bert directly instead of distilbert
- question answering with distilbert seems fine to me (and from our tests albert does not really reduce memory consumption)

**Comment by PhilipMay** [comment]
Ok. 👍

**Pull request closed without merging**
